-- 40_task_board.sql
--
-- NOT APPLIED to any deployment. Build-only, per WO-10 Task D. Our issue #22.
--
-- ══════════════════════════════════════════════════════════════════════════
-- POLICIES ARE DELIBERATELY ABSENT, AND THAT IS NOT AN OVERSIGHT
-- ══════════════════════════════════════════════════════════════════════════
-- Task visibility must reuse the RLS model applied in migration 43 --
-- can_read_row_as_request(), row_scope(), the scope registry -- rather than
-- invent a parallel one. Two authorization paths that agree on the day they are
-- written and drift afterward is a defect this project has already paid for
-- twice (the retrieval projection's own owner/visibility copies, and
-- promote_memory looking like a chokepoint while nothing gated INSERT).
--
-- Writing those policies is a separate migration and a separate review. Until
-- then these tables are protected exactly the way everything else was before
-- policies existed: RLS enabled with NO policy, which is deny-all, and all
-- privileges revoked from anon and authenticated. Reachable only via
-- service_role. That is a real posture, not a placeholder -- it is the same one
-- memories had for weeks.
--
-- The owner/visibility columns are present now so that the later policy is a
-- policy and not a schema migration.
--
-- ══════════════════════════════════════════════════════════════════════════
-- THE INVARIANT THIS SCHEMA EXISTS TO PROTECT
-- ══════════════════════════════════════════════════════════════════════════
-- A task points at data. It never carries a copy of it.
--
-- The failure being designed out: someone writes "post these three claims" and
-- pastes the claim text into the task body. A claim is later superseded. The
-- task still reads correctly, still looks actionable, and now describes
-- something that is no longer true. Nobody gets an error; they get a
-- confidently-worded instruction built from history.
--
-- Two mechanisms, and it is worth being precise about which does what:
--
--   1. STRUCTURAL: references are (ref_table, ref_id) pairs validated to exist.
--      Resolution happens at read time through task_reference_state, so a
--      superseded referent shows as stale rather than as a value.
--   2. BEST-EFFORT: a trigger rejects a task body that contains a referenced
--      row's content VERBATIM. This catches copy-paste, which is the common
--      case. It does NOT catch paraphrase, summary, or a number lifted out of a
--      sentence -- no trigger can. Stated here rather than left for someone to
--      discover, because a guard whose limits are unstated gets trusted past
--      them.
--
-- Staleness is COMPUTED, never stored. A stored is_stale flag would need
-- maintaining, and a staleness flag that is itself stale is worse than none --
-- the identical failure the retrieval projection hit with its cached ACL
-- columns (migration 39).

-- ── Lifecycle ─────────────────────────────────────────────────────────────
-- Deliberately NOT record_status. Tasks are not knowledge records: they are not
-- promoted, not superseded, not cited as fact. Reusing record_status would make
-- two different lifecycles share a vocabulary and invite guards written for one
-- to be applied to the other.
create type task_status as enum (
  'open',        -- exists, not started
  'in_progress',
  'blocked',     -- cannot proceed; see task_dependencies
  'done',        -- completed; evidence required where the task demands it
  'cancelled'    -- will not be done. Terminal, and distinct from done.
);

create type task_kind as enum (
  'action',      -- someone does a thing
  'review',      -- someone checks a thing
  'decision',    -- someone chooses
  'obligation'   -- generated by a rule, carries an external deadline.
                 -- The obligation model itself is NOT in this file.
);

-- subject vs constraint is the distinction that carries meaning. "Write a post
-- using claim X" and "write a post that must not contradict claim X" reference
-- the same row and mean opposite things. Collapsing them loses the difference
-- exactly when it matters.
create type task_ref_role as enum (
  'subject',     -- the task is ABOUT this record
  'constraint',  -- the task must RESPECT this record
  'evidence',    -- this record is proof the task was completed
  'context'      -- background; informative only
);

-- ── Which tables may be referenced ────────────────────────────────────────
-- A registry rather than a CHECK list, for the same reason provenance_registry
-- and scope_registry are registries: adding a table becomes a reviewable row
-- instead of a migration, and the set is queryable.
create table task_referenceable (
  ref_table     text primary key,
  id_column     text not null default 'id',
  status_column text,          -- null when the table has no lifecycle
  content_column text,         -- null when there is no text to compare
  description   text not null,
  registered_at timestamptz not null default now()
);

insert into task_referenceable (ref_table, status_column, content_column, description) values
 ('memories','status','content','Knowledge records'),
 ('wiki_pages','status','content','Wiki pages'),
 ('ingredient_claims',null,null,'Domain claims (sql/11). Registered without a status column: if that table later gains a lifecycle, add it here or staleness will silently under-report.');

alter table task_referenceable enable row level security;
revoke all on task_referenceable from anon, authenticated;

-- ── tasks ─────────────────────────────────────────────────────────────────
create table tasks (
  id                  uuid primary key default gen_random_uuid(),
  title               text not null check (btrim(title) <> ''),
  body                text,
  kind                task_kind not null default 'action',
  status              task_status not null default 'open',
  priority            int not null default 3 check (priority between 1 and 5),

  assigned_to         uuid references principals(id),
  created_by          uuid not null references principals(id),

  due_date            timestamptz,
  completed_at        timestamptz,
  requires_evidence   boolean not null default false,
  completion_evidence text,

  -- house governance pattern, same columns and semantics as memories
  provenance_basis    provenance_basis not null,
  citation            text,
  owner               uuid references principals(id),
  visibility          visibility_level not null default 'shared',
  workstream          text,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  -- done implies a completion time; nothing else may carry one
  constraint tasks_completed_at_matches_status
    check ((status = 'done') = (completed_at is not null)),
  -- evidence is only meaningful on a finished task
  constraint tasks_evidence_only_when_done
    check (completion_evidence is null or status = 'done')
);

create index on tasks (assigned_to) where status in ('open','in_progress','blocked');
create index on tasks (status);
create index on tasks (workstream);
create index tasks_due_idx on tasks (due_date)
  where due_date is not null and status in ('open','in_progress','blocked');

comment on table tasks is
  'Work routed between principals, human or agent. Tasks reference backend data by id and never copy it -- see task_references and task_reference_state. Not a knowledge record: not promoted, not superseded, not citable as fact.';

-- Provenance on creation, same rule as memories: a basis is required, and
-- anything that is not a direct human statement needs a citation.
create or replace function enforce_task_provenance()
returns trigger language plpgsql as $$
begin
  if new.provenance_basis <> 'human_direct'
     and (new.citation is null or btrim(new.citation) = '') then
    raise exception
      'tasks.provenance_basis=% requires a non-empty citation (task %)',
      new.provenance_basis, new.id;
  end if;
  return new;
end; $$;

create trigger trg_task_provenance
  before insert or update on tasks
  for each row execute function enforce_task_provenance();

-- ── Status lifecycle ──────────────────────────────────────────────────────
-- Explicit allowed edges. An enum alone constrains the VALUE, not the
-- TRANSITION -- a task could otherwise jump from open straight to done, or
-- return from cancelled, and the column type would be satisfied.
create or replace function enforce_task_transition()
returns trigger language plpgsql as $$
declare ok boolean;
begin
  if new.status = old.status then return new; end if;

  ok := (old.status, new.status) in (
    ('open','in_progress'), ('open','blocked'), ('open','cancelled'),
    ('in_progress','blocked'), ('in_progress','done'), ('in_progress','cancelled'),
    ('blocked','in_progress'), ('blocked','cancelled'),
    ('open','done')  -- a trivial task may be completed without being started
  );

  if not ok then
    raise exception
      'task % cannot go % -> %. Allowed: open->in_progress|blocked|done|cancelled, in_progress->blocked|done|cancelled, blocked->in_progress|cancelled. done and cancelled are terminal.',
      new.id, old.status, new.status;
  end if;

  -- Evidence is checked HERE and not only in a CHECK constraint, because the
  -- constraint cannot say "required only when the task demanded it".
  if new.status = 'done' and new.requires_evidence
     and (new.completion_evidence is null or btrim(new.completion_evidence) = '') then
    raise exception
      'task % requires completion evidence and cannot be marked done without it. This is the point of requires_evidence: a checkbox that ticks without the artifact manufactures false assurance.',
      new.id;
  end if;

  return new;
end; $$;

create trigger trg_task_transition
  before update on tasks
  for each row execute function enforce_task_transition();

-- requires_evidence must not be switchable to false to dodge the gate above.
create or replace function enforce_task_evidence_ratchet()
returns trigger language plpgsql as $$
begin
  if old.requires_evidence and not new.requires_evidence then
    raise exception
      'task %: requires_evidence cannot be turned off. It ratchets on, or the evidence gate is advisory -- someone blocked at completion would simply clear the flag.',
      new.id;
  end if;
  return new;
end; $$;

create trigger trg_task_evidence_ratchet
  before update on tasks
  for each row execute function enforce_task_evidence_ratchet();

-- ── task_references ───────────────────────────────────────────────────────
create table task_references (
  id          uuid primary key default gen_random_uuid(),
  task_id     uuid not null references tasks(id) on delete cascade,
  ref_table   text not null references task_referenceable(ref_table),
  ref_id      uuid not null,
  ref_role    task_ref_role not null,
  note        text,
  created_at  timestamptz not null default now(),
  unique (task_id, ref_table, ref_id, ref_role)
);

create index on task_references (task_id);
create index on task_references (ref_table, ref_id);

alter table task_references enable row level security;
revoke all on task_references from anon, authenticated;

comment on table task_references is
  'Polymorphic link from a task to a backend row. ref_role distinguishes subject from constraint -- the same referenced row means opposite things in each. Resolution is at read time via task_reference_state; nothing here caches the referent.';

-- A polymorphic reference cannot have a foreign key, so existence is checked by
-- trigger. Without this, a task can point at a row that never existed and the
-- staleness view reports it identically to one that was deleted.
create or replace function enforce_task_reference_exists()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_reg task_referenceable%rowtype; v_found boolean;
begin
  select * into v_reg from task_referenceable where ref_table = new.ref_table;
  if not found then
    raise exception 'ref_table % is not registered in task_referenceable', new.ref_table;
  end if;

  execute format('select exists (select 1 from public.%I where %I = $1)',
                 v_reg.ref_table, v_reg.id_column)
    into v_found using new.ref_id;

  if not v_found then
    raise exception 'task reference points at %.% = % which does not exist',
      v_reg.ref_table, v_reg.id_column, new.ref_id;
  end if;
  return new;
end; $$;

create trigger trg_task_reference_exists
  before insert or update on task_references
  for each row execute function enforce_task_reference_exists();

-- ── The no-copy guard ─────────────────────────────────────────────────────
-- Best-effort by construction, and the comment says so. It rejects a task body
-- that contains a referenced row's content verbatim, which is what copy-paste
-- produces. It cannot detect a paraphrase, a summary, or a single figure lifted
-- out of a sentence.
--
-- Short referent content is skipped: a claim whose text is "500mg" would match
-- half the sentences anyone might write, and a guard that fires constantly is
-- one that gets dropped. 40 characters is a judgement, not a derived threshold.
create or replace function enforce_task_no_embedded_copy()
returns trigger language plpgsql security definer set search_path = public as $$
declare r record; v_text text; v_reg task_referenceable%rowtype;
begin
  if new.body is null or btrim(new.body) = '' then return new; end if;

  for r in select tr.ref_table, tr.ref_id from task_references tr where tr.task_id = new.id
  loop
    select * into v_reg from task_referenceable where ref_table = r.ref_table;
    continue when v_reg.content_column is null;

    execute format('select %I from public.%I where %I = $1',
                   v_reg.content_column, v_reg.ref_table, v_reg.id_column)
      into v_text using r.ref_id;

    if v_text is not null and length(btrim(v_text)) >= 40
       and position(btrim(v_text) in new.body) > 0 then
      raise exception
        'task % body contains the verbatim content of referenced %.%. Reference it by id instead: an embedded copy goes stale the moment that record is superseded, and the task keeps reading correctly while describing something no longer true.',
        new.id, r.ref_table, r.ref_id;
    end if;
  end loop;
  return new;
end; $$;

-- Fires on the TASK, after references exist. A reference added later to a task
-- whose body already contains the text is caught by the same function via the
-- reference-side trigger below.
create trigger trg_task_no_embedded_copy
  before update on tasks
  for each row execute function enforce_task_no_embedded_copy();

create or replace function enforce_task_ref_no_embedded_copy()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_body text; v_text text; v_reg task_referenceable%rowtype;
begin
  select body into v_body from tasks where id = new.task_id;
  if v_body is null or btrim(v_body) = '' then return new; end if;

  select * into v_reg from task_referenceable where ref_table = new.ref_table;
  if v_reg.content_column is null then return new; end if;

  execute format('select %I from public.%I where %I = $1',
                 v_reg.content_column, v_reg.ref_table, v_reg.id_column)
    into v_text using new.ref_id;

  if v_text is not null and length(btrim(v_text)) >= 40
     and position(btrim(v_text) in v_body) > 0 then
    raise exception
      'cannot reference %.% from task %: the task body already contains that record''s content verbatim. Remove the copy and reference it by id.',
      new.ref_table, new.ref_id, new.task_id;
  end if;
  return new;
end; $$;

create trigger trg_task_ref_no_embedded_copy
  before insert or update on task_references
  for each row execute function enforce_task_ref_no_embedded_copy();

-- ── task_dependencies ─────────────────────────────────────────────────────
create table task_dependencies (
  task_id      uuid not null references tasks(id) on delete cascade,
  depends_on   uuid not null references tasks(id) on delete cascade,
  created_at   timestamptz not null default now(),
  primary key (task_id, depends_on),
  constraint task_dependencies_no_self check (task_id <> depends_on)
);

create index on task_dependencies (depends_on);

alter table task_dependencies enable row level security;
revoke all on task_dependencies from anon, authenticated;

-- Cycles are rejected at WRITE, not detected at read. A board that accepts a
-- cycle deadlocks silently: every task in the loop is blocked by another task
-- in the loop, nothing is actionable, and nothing reports an error. The depth
-- cap is a second guard -- a traversal that never terminates is an outage, and
-- this runs on every dependency insert.
create or replace function enforce_task_no_dependency_cycle()
returns trigger language plpgsql as $$
declare v_cycle boolean;
begin
  with recursive reach(id, depth) as (
    select new.task_id, 0
    union all
    select d.task_id, r.depth + 1
    from task_dependencies d
    join reach r on d.depends_on = r.id
    where r.depth < 64
  )
  select exists (select 1 from reach where id = new.depends_on) into v_cycle;

  if v_cycle then
    raise exception
      'dependency % -> % creates a cycle. A dependency cycle deadlocks the board silently: every task in the loop waits on another task in the loop, and nothing reports an error.',
      new.task_id, new.depends_on;
  end if;
  return new;
end; $$;

create trigger trg_task_no_dependency_cycle
  before insert or update on task_dependencies
  for each row execute function enforce_task_no_dependency_cycle();

-- ── Read surfaces ─────────────────────────────────────────────────────────
-- Staleness computed on read. A referent that is superseded, retracted or
-- entered_in_error is reported as such rather than resolved to a value.
create or replace function task_reference_state(p_task_id uuid)
returns table (reference_id uuid, ref_table text, ref_id uuid, ref_role task_ref_role,
               referent_status text, state text)
language plpgsql stable security definer set search_path = public as $fn$
-- OUT parameters share names with columns on task_referenceable, so every
-- reference to those columns is qualified. Unqualified, PostgreSQL reports
-- "column reference ref_table is ambiguous" at RUNTIME, not at creation -- the
-- function compiles fine and fails the first time it is called.
declare r record; v_reg task_referenceable%rowtype; v_status text;
begin
  for r in select tr.id   as tr_id,
                  tr.ref_table as tr_table,
                  tr.ref_id    as tr_id_val,
                  tr.ref_role  as tr_role
             from task_references tr where tr.task_id = p_task_id
  loop
    select * into v_reg from task_referenceable tf where tf.ref_table = r.tr_table;
    v_status := null;
    if v_reg.status_column is not null then
      execute format('select %I::text from public.%I where %I = $1',
                     v_reg.status_column, v_reg.ref_table, v_reg.id_column)
        into v_status using r.tr_id_val;
    end if;

    reference_id := r.tr_id; ref_table := r.tr_table; ref_id := r.tr_id_val;
    ref_role := r.tr_role; referent_status := v_status;
    state := case
       when v_status is null and v_reg.status_column is null then 'no_lifecycle'
       when v_status is null then 'missing'
       when v_status = 'current' then 'live'
       else 'stale'
     end;
    return next;
  end loop;
end; $fn$;

comment on function task_reference_state(uuid) is
  'Resolves a task''s references at READ time. A superseded or retracted referent reports state=stale rather than being silently resolved to its old value. Nothing is cached: a stored staleness flag would itself go stale, which is the defect migration 39 fixed in the retrieval projection.';

create or replace function task_board(p_principal_id uuid)
returns table (task_id uuid, title text, status task_status, kind task_kind,
               priority int, due_date timestamptz, assigned_to uuid,
               stale_references bigint, blocking_open bigint, actionable boolean)
language sql stable security definer set search_path = public as $$
  select t.id, t.title, t.status, t.kind, t.priority, t.due_date, t.assigned_to,
         (select count(*) from task_reference_state(t.id) s where s.state in ('stale','missing')),
         (select count(*) from task_dependencies d join tasks bt on bt.id = d.depends_on
           where d.task_id = t.id and bt.status not in ('done','cancelled')),
         -- Actionable means: workable now AND not resting on anything stale.
         -- A task whose subject was superseded is not actionable even if
         -- nothing blocks it, because acting on it means acting on history.
         t.status in ('open','in_progress')
         and (select count(*) from task_dependencies d join tasks bt on bt.id = d.depends_on
               where d.task_id = t.id and bt.status not in ('done','cancelled')) = 0
         and (select count(*) from task_reference_state(t.id) s
               where s.state in ('stale','missing')) = 0
  from tasks t
  where is_owner_or_shared(t.owner, t.visibility, p_principal_id)
  order by t.priority, t.due_date nulls last;
$$;

comment on function task_board(uuid) is
  'Per-principal board. Filters on the SAME owner/visibility predicate the rest of the schema uses. It does NOT yet apply capability scope -- that arrives with the RLS policies for these tables, deliberately deferred. Until then these tables are deny-all with no policy and reachable only via service_role.';

alter table tasks enable row level security;
revoke all on tasks from anon, authenticated;
revoke execute on function task_reference_state(uuid) from anon, authenticated, public;
revoke execute on function task_board(uuid) from anon, authenticated, public;
revoke execute on function enforce_task_provenance() from anon, authenticated, public;
revoke execute on function enforce_task_transition() from anon, authenticated, public;
revoke execute on function enforce_task_evidence_ratchet() from anon, authenticated, public;
revoke execute on function enforce_task_reference_exists() from anon, authenticated, public;
revoke execute on function enforce_task_no_embedded_copy() from anon, authenticated, public;
revoke execute on function enforce_task_ref_no_embedded_copy() from anon, authenticated, public;
revoke execute on function enforce_task_no_dependency_cycle() from anon, authenticated, public;
